# Server configuration
server.servlet.context-path=/foyer
server.port=8082

### DATABASE CONFIGURATION ###
spring.datasource.url=jdbc:mysql://mysqldb:3306/foyer?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Management Endpoints Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
